package tests

import (
	"strings"
	"testing"

	"github.com/peasant-labs/zone/internal/docker"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- Dockerfile Rendering Tests ---

// DOC-01: Dockerfile generated from Go text/template with go:embed
func TestRenderDockerfileBasic(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage: "ubuntu:24.04",
		HostUID:   1000,
		Shell:     "bash",
		MountPath: "/workspace",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err, "RenderDockerfile must not error")
	assert.Contains(t, result, "FROM ubuntu:24.04", "Must contain FROM with base image")
	assert.Contains(t, result, "ARG HOST_UID=1000", "Must contain HOST_UID ARG")
	assert.Contains(t, result, "ENTRYPOINT [\"/entrypoint.sh\"]", "Must contain ENTRYPOINT")
	assert.Contains(t, result, "WORKDIR /workspace", "Must contain WORKDIR")
}

// DOC-01: Generation header on line 2 (after syntax directive)
func TestRenderDockerfileGenerationHeader(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage: "ubuntu:24.04",
		HostUID:   1000,
		Shell:     "bash",
		MountPath: "/workspace",
	}
	result, err := docker.RenderDockerfile(data, "0.5.0")
	require.NoError(t, err)
	lines := strings.Split(result, "\n")
	assert.Equal(t, "# syntax=docker/dockerfile:1", lines[0], "Line 1 must be syntax directive")
	assert.Equal(t, "# Generated by zone 0.5.0 -- do not edit", lines[1], "Line 2 must be generation header")
}

// DOC-04: Non-root zone user created with UID matching host
func TestRenderDockerfileNonRootUser(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage: "ubuntu:24.04",
		HostUID:   1001,
		Shell:     "bash",
		MountPath: "/workspace",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, `existing_user="$(getent passwd "${HOST_UID}" | cut -d: -f1 || true)"`,
		"Must detect an existing user with the host UID")
	assert.Contains(t, result, `usermod -l zone "${existing_user}"`,
		"Must reuse an existing host-UID user as zone")
	assert.Contains(t, result, `useradd -m -s /bin/bash -u "${HOST_UID}" zone`,
		"Must create zone user when the host UID is unused")
	assert.Contains(t, result, "USER zone", "Must switch to zone user")
}

// DOC-05: Sudo scoped to package managers
func TestRenderDockerfileSudoScope(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage: "ubuntu:24.04",
		HostUID:   1000,
		Shell:     "bash",
		MountPath: "/workspace",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "NOPASSWD: /usr/bin/apt-get, /usr/bin/apt, /usr/bin/pip*, /usr/bin/npm, /usr/local/bin/npm",
		"Sudoers must scope to exact package manager commands per spec")
}

// DOC-16: Root UID skips user creation (CI)
func TestRenderDockerfileRootUID(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage: "ubuntu:24.04",
		HostUID:   0,
		Shell:     "bash",
		MountPath: "/workspace",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err)
	assert.NotContains(t, result, "useradd", "Must NOT create user when HostUID=0")
	assert.NotContains(t, result, "USER zone", "Must NOT switch to zone user when HostUID=0")
	assert.Contains(t, result, "Running as root (CI environment)", "Must have CI comment")
}

// DOC-15: macOS username symlink
func TestRenderDockerfileMacOSSymlink(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage:     "ubuntu:24.04",
		HostUID:       1000,
		Shell:         "bash",
		MountPath:     "/workspace",
		MacOSUsername: "johndoe",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "mkdir -p /Users/johndoe", "Must create macOS user directory")
	assert.Contains(t, result, "ln -sf /home/zone /Users/johndoe", "Must create symlink")
}

// DOC-15: No macOS block when MacOSUsername is empty
func TestRenderDockerfileNoMacOSOnLinux(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage:     "ubuntu:24.04",
		HostUID:       1000,
		Shell:         "bash",
		MountPath:     "/workspace",
		MacOSUsername: "",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err)
	assert.NotContains(t, result, "/Users/", "Must NOT have macOS block when MacOSUsername is empty")
}

// Dockerfile with optional packages
func TestRenderDockerfileWithPackages(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage:   "ubuntu:24.04",
		HostUID:     1000,
		Shell:       "bash",
		MountPath:   "/workspace",
		AptPackages: []string{"vim", "tmux"},
		NpmPackages: []string{"typescript", "eslint"},
		PipPackages: []string{"black", "mypy"},
		NeedsNode:   true,
		NodeVersion: "20",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "vim", "Must include apt packages")
	assert.Contains(t, result, "tmux", "Must include apt packages")
	assert.Contains(t, result, "npm install -g typescript eslint", "Must join npm packages with space")
	assert.Contains(t, result, "pip install --break-system-packages black mypy", "Must join pip packages with space")
	assert.Contains(t, result, "setup_20.x", "Must include node version")
}

// Dockerfile with harness install commands
func TestRenderDockerfileWithHarnessInstall(t *testing.T) {
	data := docker.DockerfileData{
		BaseImage:              "ubuntu:24.04",
		HostUID:                1000,
		Shell:                  "bash",
		MountPath:              "/workspace",
		HarnessInstallCommands: []string{"curl -fsSL https://example.com/install.sh | sh", "chmod +x /usr/local/bin/harness"},
		HealthCheck:            "harness --version",
	}
	result, err := docker.RenderDockerfile(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "Harness installation", "Must have harness install section")
	assert.Contains(t, result, "harness --version", "Must include health check")
}

// --- Entrypoint Rendering Tests ---

// DOC-02: Entrypoint ends with exec sleep infinity to keep container alive
func TestRenderEntrypointExec(t *testing.T) {
	data := docker.EntrypointData{
		MountPath:         "/workspace",
		EntrypointCommand: "claude",
		Shell:             "bash",
	}
	result, err := docker.RenderEntrypoint(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "exec sleep infinity", "Must keep container alive for docker exec attach")
}

// DOC-13: Git safe.directory configured
func TestRenderEntrypointGitSafeDir(t *testing.T) {
	data := docker.EntrypointData{
		MountPath:         "/workspace",
		EntrypointCommand: "claude",
		Shell:             "bash",
	}
	result, err := docker.RenderEntrypoint(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "git config --global --add safe.directory /workspace",
		"Must configure git safe.directory for workspace mount")
}

// DOC-14: Git identity forwarded when present
func TestRenderEntrypointGitIdentity(t *testing.T) {
	data := docker.EntrypointData{
		MountPath:         "/workspace",
		ForwardGitConfig:  true,
		GitUserName:       "Test User",
		GitUserEmail:      "test@example.com",
		EntrypointCommand: "claude",
		Shell:             "bash",
	}
	result, err := docker.RenderEntrypoint(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, `git config --global user.name "Test User"`, "Must forward git user.name")
	assert.Contains(t, result, `git config --global user.email "test@example.com"`, "Must forward git user.email")
}

// DOC-14: Git identity NOT forwarded when ForwardGitConfig=false
func TestRenderEntrypointNoGitIdentity(t *testing.T) {
	data := docker.EntrypointData{
		MountPath:         "/workspace",
		ForwardGitConfig:  false,
		EntrypointCommand: "claude",
		Shell:             "bash",
	}
	result, err := docker.RenderEntrypoint(data, "1.0.0")
	require.NoError(t, err)
	assert.NotContains(t, result, "user.name", "Must NOT forward git user.name when disabled")
	assert.NotContains(t, result, "user.email", "Must NOT forward git user.email when disabled")
}

// Entrypoint generation header
func TestRenderEntrypointGenerationHeader(t *testing.T) {
	data := docker.EntrypointData{
		MountPath:         "/workspace",
		EntrypointCommand: "claude",
		Shell:             "bash",
	}
	result, err := docker.RenderEntrypoint(data, "0.3.0")
	require.NoError(t, err)
	assert.Contains(t, result, "# Generated by zone 0.3.0 -- do not edit", "Must have generation header with version")
}

// Entrypoint with zsh shell sources .zshrc
func TestRenderEntrypointZshShell(t *testing.T) {
	data := docker.EntrypointData{
		MountPath:         "/workspace",
		EntrypointCommand: "claude",
		Shell:             "zsh",
	}
	result, err := docker.RenderEntrypoint(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, ".zshrc", "Must source .zone-bashrc in .zshrc when shell is zsh")
}

// --- ShellRC Rendering Tests ---

// DOC-03: Shell RC has ZONE_HARNESS export and aliases
func TestRenderShellRCBasic(t *testing.T) {
	data := docker.ShellRCData{
		HarnessName: "claude-code",
		MountPath:   "/workspace",
		Aliases: map[string]string{
			"ll": "ls -la",
		},
	}
	result, err := docker.RenderShellRC(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, `export ZONE_HARNESS="claude-code"`, "Must export ZONE_HARNESS")
	assert.Contains(t, result, `export ZONE_WORKSPACE="/workspace"`, "Must export ZONE_WORKSPACE")
	assert.Contains(t, result, `alias ll="ls -la"`, "Must include alias definitions")
}

// ShellRC with custom welcome message
func TestRenderShellRCWelcomeMessage(t *testing.T) {
	data := docker.ShellRCData{
		HarnessName:    "claude-code",
		MountPath:      "/workspace",
		WelcomeMessage: "Welcome to Zone!",
	}
	result, err := docker.RenderShellRC(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "Welcome to Zone!", "Must show custom welcome message")
	assert.Contains(t, result, "ZONE_WELCOMED", "Must guard welcome with ZONE_WELCOMED var")
}

// ShellRC with default welcome (no custom message)
func TestRenderShellRCDefaultWelcome(t *testing.T) {
	data := docker.ShellRCData{
		HarnessName: "claude-code",
		MountPath:   "/workspace",
	}
	result, err := docker.RenderShellRC(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, "Zone workspace: claude-code", "Must show default welcome with harness name")
	assert.Contains(t, result, "Workspace: /workspace", "Must show default welcome with workspace path")
}

// ShellRC prompt
func TestRenderShellRCPrompt(t *testing.T) {
	data := docker.ShellRCData{
		HarnessName: "aider",
		MountPath:   "/workspace",
	}
	result, err := docker.RenderShellRC(data, "1.0.0")
	require.NoError(t, err)
	assert.Contains(t, result, `[zone:aider]`, "Must include harness name in PS1 prompt")
}
