// dockerfile.go generates Dockerfiles from Go templates.
package docker

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/peasant-labs/zone/pkg/templates"
)

// DockerfileData holds all variables consumed by Dockerfile.tmpl.
// Harness-specific fields (HarnessInstallCommands, HealthCheck, etc.) are populated
// by the harness system in Phase 5. Phase 4 tests populate them directly.
type DockerfileData struct {
	BaseImage              string
	HostUID                int
	AptPackages            []string
	NeedsNode              bool
	NodeVersion            string
	NeedsPython            bool
	PythonVersion          string
	NpmPackages            []string
	PipPackages            []string
	HarnessInstallCommands []string
	HealthCheck            string
	InstallZsh             bool
	Shell                  string
	MacOSUsername          string   // empty string = skip macOS symlink block
	PostInstallCommands    []string
	MountPath              string
}

// templateFuncs returns the FuncMap required by all zone templates.
// "join" is used in Dockerfile.tmpl for NpmPackages, PipPackages, etc.
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"join": strings.Join,
	}
}

// RenderDockerfile renders the Dockerfile template with the given data.
// The generation header is injected on line 2, after the # syntax= directive.
// Returns the complete rendered Dockerfile as a string.
func RenderDockerfile(data DockerfileData, version string) (string, error) {
	tmpl, err := template.New("Dockerfile").Funcs(templateFuncs()).Parse(templates.DockerfileTmpl)
	if err != nil {
		return "", fmt.Errorf("parse Dockerfile template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render Dockerfile: %w", err)
	}
	return injectGenerationComment(buf.String(), version), nil
}

// injectGenerationComment inserts the generation header comment after the first
// line when it is a directive (# syntax= for Dockerfiles, #! for scripts).
// This preserves the shebang on line 1 so the OS can find the interpreter.
func injectGenerationComment(rendered, version string) string {
	header := "# Generated by zone " + version + " -- do not edit"
	lines := strings.SplitN(rendered, "\n", 2)
	if len(lines) >= 2 && (strings.HasPrefix(lines[0], "# syntax=") || strings.HasPrefix(lines[0], "#!")) {
		return lines[0] + "\n" + header + "\n" + lines[1]
	}
	return header + "\n" + rendered
}
